//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInventoryBySku
    {
        public System.Guid Id { get; set; }
        public string ModelNumber { get; set; }
        public string Variant { get; set; }
        public string Description { get; set; }
        public bool ProductActive { get; set; }
        public Nullable<int> QuantityOnReserve { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public Nullable<int> MinimumQuantityAvailable { get; set; }
        public bool InventoryActive { get; set; }
        public string Value { get; set; }
        public bool StatusTypeActive { get; set; }
    }
}
